import { Router } from 'express';
import authRoutes from './auth.routes';
import userRoutes from './user.routes';
import restaurantRoutes from './restaurant.routes';
import menuRoutes from './menu.routes';
import orderRoutes from './order.routes';
import reviewRoutes from './review.routes';
import roleRoutes from './role.routes';
import deliveryRoutes from './delivery.routes';
import cartRoutes from './cart.routes';
import paymentRoutes from './payment.routes';
import adminRoutes from './admin.routes';
import ownerRoutes from './owner.routes';

const router = Router();
router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/restaurants', restaurantRoutes);
router.use('/menu', menuRoutes);
router.use('/orders', orderRoutes);
router.use('/reviews', reviewRoutes);
router.use('/feedbacks', reviewRoutes);
router.use('/roles', roleRoutes);
router.use('/deliveries', deliveryRoutes);
router.use('/cart', cartRoutes);
router.use('/payments', paymentRoutes);
router.use('/admin', adminRoutes);
router.use('/owner', ownerRoutes);
export default router;
